### ISSUE TITLE
Caregiver Status Page - Design

### ISSUE THREAD

**Issue by alexandrugavril** [alexandrugavril/CamiAndroidApp#12]

**Comment by asorici** [comment]
Status page must be able to display the graphs for the following additional measurements:
  - step count (per day)
  - slept hours (per day)

They should be displayed using a bar chart.

**Comment by asorici** [comment]
The graphs must include a **horizontal line** marking the **average value** for the displayed measurement history.

**Comment by alexandrugavril** [comment]
Type = Steps / Type = Sleep
