### ISSUE TITLE
CAMI Caregiver Activities Page - Design

### ISSUE THREAD

**Issue by asorici** [alexandrugavril/CamiAndroidApp#16]
The Activities tab should be implemented using the [ListView](https://fullcalendar.io/releases/fullcalendar/3.9.0/demos/locales.html) format of fullcalendar.io.

It must respect the following specifications:
  - the calendar shows Activities retrieved from the CAMI cloud, from _one week before_ to _one week after_ the current day
  - the current activity (if any) must be highligthed
  - previous activities should appear in a _shaded_ nuance
  - the view **must** use the locale (en, ro, pl, dk) for the text on the UI elements
    - the locale can be obtained from the user endpoint of the CAMI API

**Comment by alexandrugavril** [comment]
https://scontent-otp1-1.xx.fbcdn.net/v/t34.0-12/28537291_10213789503646247_934383573_n.jpg?oh=a2494704b2cb9906f5e590a1ecd1a555&oe=5AA3BE5A
