### ISSUE TITLE
UI locales in CAMI Android App

### ISSUE THREAD

**Issue by asorici** [alexandrugavril/CamiAndroidApp#18]
### Why
In the field tests of CAMI, the end-user partners have strongly requested that the mobile app support localization (that is, UI and content must be translated in the native language) because not all elderly user are accustomed to english.

The content is already localized based on the user you sign in with.
We need to adapt the text of each UI element (e.g. on buttons or tabs) to the language of each end-user.

### What
  - a translation dict for UI elements is created at application level
  - the appropriate UI element text is used based on the _language_ value in the enduser_profile specification

### Notes
When accessing the `user` endpoint (e.g. for [camidemo](http://cami.vitaminsoftware.com:8008/api/v1/user/2/)) the language abbreviation can be obtained from the  `enduser_profile['language']` key

**Comment by alexandrugavril** [comment]
I've added translations.js -> you need to add a key and the corresponding UI translations in that dictionary there.
