### ISSUE TITLE
Add translation into Polish

### ISSUE THREAD

**Issue by asorici** [alexandrugavril/CamiAndroidApp#28]
no_new_reminders: "Nie masz nowych powiadomień!",
        heart_rate: "Tętno",
        weight: "Waga",
        blood_pressure: "Ciśnienie",
        diastolic: "Rozkurczowe",
        systolic: "Skurczowe",
        latest_value: "Ostatni pomiar:",
        next: "Dalej",
        home: "Strona Główna",
        status: "Status",
        journal: "Dziennik",
        activities: "Aktywności",
        logout: "Wyloguj",
        username: "Nazwa użytkownika",
        password: "Hasło",
        login: "Zaloguj"
        back: "Wróć",
        all_is_fine: "Wszystko jest w porządku"
        steps: "Kroki",
        sleep: "Sen",
        welcome: "Witaj",

**Comment by alexandrugavril** [comment]
Please mention the abbreviation as well in order to match the CAMI end-point.
