### ISSUE TITLE
Latest Notification Tab Design

### ISSUE THREAD

**Issue by alexandrugavril** [alexandrugavril/CamiAndroidApp#4]
- Displays the latest received notification, if and only if, the notification timestamp is within 30 minutes of the current time
- If more than 30 minutes have passed since the latest notification, the tab will display a No new notifications message and a link to the history notifications
- For an active notification, the user has two buttons at his disposal. The text and purpose of the buttons changes depending on the message type (JournalEntry)
  - For reminders (Journal Entry type = medication, exercise, appointment)
    - OK - acknowledge the reminder
    - Cancel - cancel the reminder 
  - For notifications (Journal Entry type = weight, heart, steps, sleep, health-measurement)
    - OK - acknowledge the notification
    - Help - start a call to caregiver (not implemented yet)

**Comment by asorici** [comment]
The notifications (Journal Entry type = weight, heart, steps, sleep, health-measurement) must **not** have a Help button (since that functionality is not implemented).
We keep the OK and Cancel buttons for all type of Journal Entries.
