### ISSUE TITLE
Notification History Tab Design

### ISSUE THREAD

**Issue by alexandrugavril** [alexandrugavril/CamiAndroidApp#6]
Displays a list of the notifications/reminders received today
Each item in the list displays:
- Icon - symbol coding for the notification/reminder it refers to
- Time at which it was received received
- Status: acknowledged | cancelled | ignored (i.e. no interaction)
- The text of each item displays only the title of the corresponding JournalEntry
- The item is clickable. Upon click, a new window or a pop-up view with a layout identical to that of the Latest Notification Tab appears
- The user can thus acknowledge/cancel past notifications

**Comment by asorici** [comment]
The following things still need to be handled:
  - implement a scrollbar view (or a similar UI element) that indicates that there is a list view to be consumed there
  - investigate bug related to clicking on a list item that corrupts further tab navigation.

**Comment by asorici** [comment]
To replicate bug do the following:
  - login to the application
  - switch to the JournalTab
  - single tap on a list Item
    - observed effect is that the Login and HomeTab views overlap and navigation between tabs looks broken (though it may the case that tab switching actually works, but the views do not refresh or get overlapped)

**Comment by alexandrugavril** [comment]
Get all reminders / Add visual cue for the current state True / False / Null
