### ISSUE TITLE
Login Functionality

### ISSUE THREAD

**Issue by alexandrugavril** [alexandrugavril/CamiAndroidApp#9]
The application should Post the login information to the CAMI Endpoint along with the Application registration ID for notifications.

**Comment by asorici** [comment]
To make things easy at login (i.e. perform no prior user registration from the mobile client side), I propose the following set of steps:

1. User logs in using a username + password combination
    - _username_ is the same as the username or email on the serverside (see JSON output of following call: http://139.59.181.210:8008/api/v1/user/2/

    - password is checked "**only client side**" :-) and is hardcoded to the word "**imac**"

    - if the filter request (e.g. http://139.59.181.210:8008/api/v1/user/?username=<username> returns a list with a single element, then the login is considered successful. 
From the returned JSON message the _**id**_ field is retrieved.

    - the mobile client performs a post request containing the user uri, the registration id and the notification type ("GCM")
      - if the post returns a 201, it means the new registration id has been added
      - if it returns a 4xx error, it means the registration id has not changed from the last login time

### Note
For documentation on CAMI Cloud endpoints see: http://139.59.181.210:8008/api/documentation/

**Comment by alexandrugavril** [comment]
avaliable users: camidemo / camicare

**Comment by asorici** [comment]
I will consider this done.
There was the additional issue of keeping the _logged in_ state when moving the app in the background.
I know that to be solved as well, but if it is not I will open a separate issue.
